### ISSUE TITLE
Reindexing

### ISSUE THREAD

**Issue by alijagerin** [kimios/kimios#10]
If you hit Reindex under Administration page document body will not be indexed. Adding new document and trash / untrash will index meta-data and body as expected.

**Comment by devtom30** [comment]
We have to disable this button because it is functional only if Kimios is launched in a Karaf container. 
I think you have launched Kimios in a Tomcat container and in this configuration, nothing is done when hitting the button. I think we will hide it or at less disable it because it's bad like that. 
Thank you for having signaled the problem
